### ISSUE TITLE
Add drive command to drivetrain

### ISSUE THREAD

**Issue by LateAlways** [Ultime5528/Betabots2023Swerve#2]

**Comment by ThomasMcDonald904** [comment]
J'ai pensé que sa serait cool d'avoir un bouton pour switch entre field relative et _tank drive_. 
Field relative(ce qui est implementé en ce moment):
https://github.com/Ultime5528/Betabots2023Swerve/assets/53022931/177d900a-ecd3-4346-a1b8-f07633ceb645
Tank drive: 
https://github.com/Ultime5528/Betabots2023Swerve/assets/53022931/2fa5a825-ec3e-4e42-b4b9-f915fc640a05

Dans la commande drive il faut changer la fonction finale à:
self.drivetrain.drive(x_speed, y_speed, rot, **False**, self.get_period())
